### ISSUE TITLE
System chrome is not consistent when switching between screens

### ISSUE THREAD

**Issue by hvthhien** [bitmark-inc/autonomy-apps#102]
The System chrome sometimes appears and disappears unexpectedly when switching between screens.
- During opening the home page or the settings page, when scrolling down, the system chrome will be hidden.
- When navigating to another screen, the system chrome should be restored to normal and keep the previous state when returning to the home/settings.

**Comment by NekhDRej** [comment]
The bug is not fixed on iOS. The system chrome is hidden on the home screen after scrolling on the settings page and switching to the home page
P.S. Bug is not repro on the Android

Environment:
iOS build (App center): 0.29.10 (66)
iPhone 12\iOS 15.5 - not fixed
Android build (App center): 0.29.10 (62)
Redmi 8A\Android 10 - fixed

**Comment by NekhDRej** [comment]
The bug is not fixed.
Steps to reproduce:
- Go to the settings
- Scroll down the setting
- Tap on the place of the Hamburger menu icon
- Pay attention to the result

Environment:
iOS build (App center): 0.30.0 (67)
iPhone 12\iOS 15.5 - not fixed
Android build (App center): 0.30.0 (63)
Redmi 8A\Android 10 - not fixed

https://user-images.githubusercontent.com/101094775/177130175-7566e2c6-4b7c-44c7-8804-00bae50fba59.mp4

**Comment by NekhDRej** [comment]
The bug is fixed

iOS build (App center): 0.30.1 (68)
iPhone 12\iOS 15.5
Android build (App center): 0.30.1 (64)
Redmi 8A\Android 10
