### ISSUE TITLE
Sometime, artworks collection cannot load the artwork thumbnails

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1574]
Pre-conditions:
1. Please make sure the account has some artworks to display thumbnails

Steps:
1. Navigate to artwork Collections
2. Open an artwork detail
3. Back to Collections page

Observed result:
Artworks Collections page cannot load artwork thumbnails

Expected result:
Artwork Collections should load thumbnail correctly

https://user-images.githubusercontent.com/109057362/188543219-9649fb4c-6948-4091-b35b-c95340fd15a2.MOV

**Comment by hungqd** [comment]
@longbmk, I just fixed this issue, please help recheck with latest build.
For some artwork, the thumbnail is not returns correctly, the app will show the error icon.
Please help check if the thumbnail url is valid (by opening in external browsers like Firefox, Chrome, or Postman...), since the app can't make sure all artwork can be loaded.
