### ISSUE TITLE
Gray conners appeared in the action sheet

### ISSUE THREAD

**Issue by anhnguyenbitmark** [bitmark-inc/autonomy-apps#171]
![image](https://user-images.githubusercontent.com/24427942/177235830-ff3b8dfb-224b-46af-aab7-d533b8c6c3e1.png)

**Comment by NekhDRej** [comment]
The bug is not fixed. The corners are still appeared in the action sheet

Environment:
iOS build (App center): 0.31.1 (75)
iPhone 12\iOS 15.5 - not fixed
Android build (App center): 0.31.1 (70)
Redmi 8A\Android 10 - not fixed

![corner_issue](https://user-images.githubusercontent.com/101094775/181194586-e896682c-9443-4bf8-bab7-1fcc475fdc49.png)
