### ISSUE TITLE
Order of thumbnails in Collections change after some time reloading

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1748]
Please use Vanto tz address to see this issue, artwork display then disappear, then reappear. It make the order of thumbnails change.

Vanto feedback: Order of thumbnails in collection shouldn’t change after reloading

**Comment by hungqd** [comment]
Hi @lemonlatte, can we update the indexer API to support token acquired time for each user?
Currently, if someone acquire a fungible token, the `lastUpdatedAt` is changed, make the order of token in the app is changed unexpectedly.

Btw, could you help check `/nft/owned` API, since it doesn't return all of my onwed tokens.
- https://nft-indexer.bitmark.com/nft/owned?owner=tz1d2mQ6FcKkGu6vqxN8cmYQs632YAci7NRV => 16 tokens. (expected is 40 tokens)
- https://nft-indexer.bitmark.com/nft?owner=tz1d2mQ6FcKkGu6vqxN8cmYQs632YAci7NRV => 40 tokens
