### ISSUE TITLE
Missing artist name in the push notification message of Discovery

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1772]
It should be "Artist 'artist_name' you collect just acquired a new artwork. Tap to discover".
![image](https://user-images.githubusercontent.com/109057362/193729353-f51789bc-d462-4d66-a091-9e8f58c503f9.png)

**Comment by hxw** [comment]
The artist name is not available to the event feed. So it will be necessary to add a more complex process to fetch data from the indexer. Probably better to redesign the event handling as a a series of cadence workflows since it could take some time.

Does this need to consolidate multiple artists into one message, e.g., if you have events from 10 different artists covering 15 different messages over 10 min how many events should be generated? 

I would estimate 2 or 3 points to do this work

**Comment by hxw** [comment]
Just to note, the current indexer workflow only returns error status. If it could be modified to return artist/artwork then maybe the current code could be reused and just set these in the notification. Though the rate-limiting and/or grouping would need to be addressed. On Android,I saw the each notification was a separate line and clicking any would open discovery at the most recent. I would have to manually clear the rest, so it would be better if there was only one outstanding notification.

**Comment by longbmk** [comment]
As the discussion with Jim, I will close this ticket. The function will be handled in the another ticket.
