### ISSUE TITLE
There is an artwork display too small in Mobile app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1854]
- [ ] demo-tv-tez-KT1WgvCKC8vvjbAYEgaXHo9A6GprKDyaw7N3-60060580017880624770962627646403302072539318246431997060261798457870575375965
https://user-images.githubusercontent.com/109057362/198530819-c9591f3e-b771-4691-bdf2-57d243b50f7d.MP4

- [ ] demo-tv-bmk--52189b207da5906d7f751171c25929ea5ea34e11a9a43c5ff0d9a087bc9a588e
![IMG_0620](https://user-images.githubusercontent.com/109057362/198952849-44882443-6998-4727-8ad1-04221e399c82.PNG)

**Comment by hungqd** [comment]
This is not a bug, because content of video just like that.
https://cdn.feralfileassets.com/previews/8c4c67da-9f35-4c93-9165-0caca11a8b61/1661361483/preview.mp4
<img width="1624" alt="Screen Shot 2022-10-28 at 16 01 23" src="https://user-images.githubusercontent.com/12369158/198548818-6f758f6d-bd21-47e1-9a19-97e2dbe9a91d.png">

**Comment by longbmk** [comment]
We have it in a big show. Can you please help to confirm and find solution to fix it @anhnguyenbitmark

**Comment by ritawu91** [comment]
@longbmk The original content is 1280 × 720 pixels
