### ISSUE TITLE
Sometimes, the Log of "Report bug" function is not sent and it make the support function cannot work unless we remove the Au app

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#1942]
This bug sometimes happens and we cannot get a log when it happens. Please kindly review the code and find more solutions for it.

**Comment by phuocbitmark** [comment]
@Anais-bitmark what should we do if we failed to send a message no matter how many time we tried it

**Comment by Anais-bitmark** [comment]
@phuocbitmark Is it sending a message that would fail or sending the debug log ? 
What is the reason a message would fail to be sent?

**Comment by phuocbitmark** [comment]
@Anais-bitmark, it happened while we were sending debug log. But i think we should design for a general message fails to send for unknown reason. Because right now, if it fails to send a message, it would resend it. It's not a problem if it eventually sends that message successfully. But while it's still trying to send a message, the next message cant be sent. So we need to allow users to cancel/delete that first message so they can send next message

**Comment by Anais-bitmark** [comment]
@phuocbitmark @anhnguyenbitmark 

Does it solve the problem?

[Figma](https://www.figma.com/file/jhmE5oty8Ias0QUu0uIdah/Au-bug_1942%3A-Sometimes%2C-the-Log-of-%22Report-bug%22-function-is-not-sent...?node-id=0%3A1&t=hiui9Ml8ASKGxoQE-1)

<img width="931" alt="Capture d’écran 2022-12-09 à 13 46 25" src="https://user-images.githubusercontent.com/61187455/206716199-d1cdff77-ce83-45cf-9661-c24b0f1009fc.png">

**Comment by phuocbitmark** [comment]
[0.5 units] add retry, cancel message feature

**Comment by longbmk** [comment]
This bug is very hard to test. I will retest this bug in some next builds when doing testing and facing this issue. For now, The request is no longer fail and I can't test.
