### ISSUE TITLE
There are some ERC721 NFTs miss Provenance data after purchasing the token from Objkt

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#2691]
Steps:
1. Connect to Objkt by Beacon connect
2. Confirm to buy a NFT token (tokens that have attributes)
3. Wait for the token confirmed in Autonomy
4. Open the token and find the provenance section

Observed result:
Missing the provenance section in the NFT token

Expected result:
The new purchasing token should have full provenance data.

Please use my address to check:
https://indexer.autonomy.io/v2/nft?owner=tz1dBwDL1Ze9zKtfBdiS1WcLZrqDjfgqBUuR

**Comment by lemonlatte** [comment]
@longbmk there are two cases in this issue:
1. the token is fungible, it is not solved since the provenance will by null by design.
2. the token is non-fungible, this should be solved if the client attach the pending token when they purchase by using autonomy. In the pending token follow-up process, we do a full token provenance refreshing.

**Comment by lemonlatte** [comment]
@longbmk This should also consider as done.

**Comment by moskovich** [comment]
Do you mean FA2 here?

**Comment by longbmk** [comment]
Let me check. Thank you Jim. 

May I ask about the existing token missing Provenance in indexer? Did you migrate it, @lemonlatte?

**Comment by lemonlatte** [comment]
> Let me check. Thank you Jim.
> 
> May I ask about the existing token missing Provenance in indexer? Did you migrate it, @lemonlatte?

@longbmk I do not migrate. Let me check a bit how many are missing in the db
