### ISSUE TITLE
Increase speed of stamping postcard

### ISSUE THREAD

**Issue by moskovich** [bitmark-inc/autonomy-apps#2961]
Let's get this as close as possible to the block confirmation time limit. 

[Design](https://www.figma.com/file/CFJSI2wi9dZdrMQzt9HedE/Autonomy-%232961-%2F-MoMA-%2F-Increase-stamping-speed?type=design&node-id=0%3A1&mode=design&t=JgT3z3jZmPzPSDnc-1).

**Comment by anhnguyenbitmark** [comment]
@bitmark-inc/autonomy-mobile: Client Updates:
1. Implement asynchronous stamping for instant postcard sharing, bypassing blockchain confirmation delay.
2. Consider delaying second claims to post-onboarding, prompting users to fully understand "How it works" before claiming.
3. Enhance error messages for failed claims due to pending blockchain confirmation.

**Comment by ppupha** [comment]
@bencebitmark please add design for this.

**Comment by phuocbitmark** [comment]
@bencebitmark we should call for this, this time we have to consider the risk of creating new bug

**Comment by bencebitmark** [comment]
@ppupha i'll add any new errors and screens.

@phuocbitmark i'd defer the technical side of this to @anhnguyenbitmark. if there's anything that'd affect the user flow outside the above scope, let's discuss.

**Comment by longbmk** [comment]
Checklist: 
- [ ] User can share the postcard immediately after stamping
- [ ] Thumbnail sharing shows an old thumbnail when Stamp is not confirmed
- [ ] Thumbnail sharing shows a new thumbnail when Stamp is confirmed
- [ ] Continue button at Postcard onboarding displays when the previous stamp confirmed in indexer
- [ ] Confirming on Blockchain button instead of Continue button displays when the previous stamp has not been confirmed in indexer yet.

**Comment by longbmk** [comment]
[Bug] User cannot download the new stamp when it is not confirmed.
[Bug] The downloaded postcard does not contain the new stamps when it is not confirmed

**Comment by longbmk** [comment]
@bencebitmark We have a technical issue. This bug happens and we can't fix it, but maybe it rarely happens.
This happens when you stamp immediately after claim and share immediately (it just in some seconds). CC @anhnguyenbitmark @ppupha for this
![IMG_0341](https://github.com/bitmark-inc/autonomy-apps/assets/109057362/01205417-ee9f-49c4-b161-aaa3dda51ef1)

**Comment by bencebitmark** [comment]
@longbmk 

> This bug happens and we can't fix it, but maybe it rarely happens

we worked through this with @ppupha today. it sounds like the scenario it could happen is unlikely. but we have a flow accounting for it now.
