### ISSUE TITLE
Postcard - Term & conditions navigate to Github instead of opening the webview to load Term and conditions

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#3051]
1. Scan a postcard/open a postcard detail page
2. Click on the Term & Conditions link in Onboarding postcard/Rights section
3. Observe the display

Observed result:
It shows Github link.

Expected result:
It should show the term and condition in in-app webview to load Markdown content

**Comment by anhnguyenbitmark** [comment]
Since the link is in a single line (formatted text), we can add a condition to control opening whether webview or the built-in GitHub document page as following rule:
- if the link starts with `https://github.com/bitmark-inc` and ends with `.md`, open the built-in GitHub document page.
- Otherwise, open the external native browser.

**Comment by longbmk** [comment]
[Bug] It still open Github link when clicking on Term & Conditions in Rights section of Postcard Detail page
