### ISSUE TITLE
Sometime, support server and ipfs server have problem 503-Service Temporarily Unavailable

### ISSUE THREAD

**Issue by longbmk** [bitmark-inc/autonomy-apps#3111]
Please kindly help to check this issue. You can query the failed time in monitor channel.
Thank you
GET https://support.autonomy.io/v1/issues [503]
{
duration: 0:00:01.594908, 
reason: Service Temporarily Unavailable, 
response_body_size: 190
}

**Comment by hxw** [comment]
As far as I can tell this is not from customer support service or from the gin framework since 503 is not used by their code.

The `503 Service Unavailable` error is likely originating from ingress-nginx because it no longer has a connection to the service. It is possible that the service crashed and restarted, if this happens there will be at least 2 minutes before the service will be ready. It should be possible to check this after detecting a 503, by checking the service AGE field in k9s to see if a restart actually happened and reset the time back to zero.
