### ISSUE TITLE
Survey pops-up during onboarding

### ISSUE THREAD

**Issue by anhnguyenbitmark** [bitmark-inc/autonomy-apps#59]
Survey was overlaying the onboarding. Users might have clicked on the survey and missed the onboarding.

Steps:
1. Go to Settings page, click Forget I exist to remove the current data (remind to backup the seed if needed). If you have a new phone, skip this step.
2. During the onboarding step, the survey notification shows up.

Expected:
- The survey notification should show up when user finished their onboarding and go to the home page.

**Comment by hienphan1472** [comment]
Wait for `forget I exist` feature to verify onboarding flow

**Comment by NekhDRej** [comment]
The bug is partly fixed.
Actual result: The Survey pops-up is shown only after opening the app for the second time
'Expected result:' The Survey pops-up is shown on the Collection page right after the onboarding

Environment:
iOS build (App center): 0.30.0 (67)
iPhone 12\iOS 15.5 
Android build (App center): 0.30.0 (63)
Redmi 8A\Android 10

**Comment by NekhDRej** [comment]
The bug is fixed.

Environment:
iOS build (App center): 0.31.1 (75)
iPhone 12\iOS 15.5
Android build (App center): 0.31.1 (70)
Redmi 8A\Android 10
